flat_linking_inputs.Rmd:
  path: dev/flat_linking_inputs.Rmd
  state: active
  R:
  - R/link_inputs.R
  - R/list_raw_flat_dhs.R
  - R/list_raw_gps_covars.R
  - R/list_raw_gps_dhs.R
  tests:
  - tests/testthat/test-link_inputs.R
  - tests/testthat/test-list_raw_gps_dhs.R
  - tests/testthat/test-list_raw_flat_dhs.R
  - tests/testthat/test-list_raw_gps_covars.R
  vignettes: vignettes/linking-and-tracking-raw-inputs.Rmd
  inflate:
    flat_file: dev/flat_linking_inputs.Rmd
    vignette_name: Linking and Tracking Raw Inputs
    open_vignette: false
    check: false
    document: true
    overwrite: ask
    clean: ask
    codecov: false
flat_load_dhs_data.Rmd:
  path: dev/flat_load_dhs_data.Rmd
  state: active
  R:
  - R/load_flat_dhs_data.R
  - R/load_gps_covars.R
  - R/summarize_dhs_flat_dictionary.R
  tests:
  - tests/testthat/test-load_flat_dhs_data.R
  - tests/testthat/test-summarize_dhs_flat_dictionary.R
  - tests/testthat/test-load_gps_covars.R
  vignettes: vignettes/reading-in-files-from-dhs.Rmd
  inflate:
    flat_file: dev/flat_load_dhs_data.Rmd
    vignette_name: Reading in Files from DHS
    open_vignette: false
    check: false
    document: true
    overwrite: ask
    clean: ask
    codecov: false
