# WARNING - Generated by {fusen} from dev/flat_load_dhs_data.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("load_gps_covars works", {
  expect_true(inherits(load_gps_covars, "function")) 
})
