# WARNING - Generated by {fusen} from dev/flat_load_dhs_data.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("summarize_dhs_flat_dictionary works", {
  expect_true(inherits(summarize_dhs_flat_dictionary, "function")) 
})
