# WARNING - Generated by {fusen} from dev/flat_linking_inputs.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("list_raw_gps_covars works", {
  expect_true(inherits(list_raw_gps_covars, "function")) 
})
