# WARNING - Generated by {fusen} from dev/flat_linking_inputs.Rmd: do not edit by hand # nolint: line_length_linter.

#' Title
#' 
#' Description
#' 
#' @return
#' 
#' @export
#' @examples
#' list_raw_flat_mis()
list_raw_flat_mis <- function(){
    
    c(
      # 2011
      here("data", "DHS Data", "MIS 2011", "MDHR61FL"),
      here("data", "DHS Data", "MIS 2011", "MDIR61FL"),
      here("data", "DHS Data", "MIS 2011", "MDKR61FL"),
      here("data", "DHS Data", "MIS 2011", "MDPR61FL"),
      # 2013
      here("data", "DHS Data", "MIS 2013", "MDHR6AFL"),
      here("data", "DHS Data", "MIS 2013", "MDIR6AFL"),
      here("data", "DHS Data", "MIS 2013", "MDKR6AFL"),
      here("data", "DHS Data", "MIS 2013", "MDPR6AFL"),
      # 2016
      here("data", "DHS Data", "MIS 2016", "MDHR71FL"),
      here("data", "DHS Data", "MIS 2016", "MDIR71FL"),
      here("data", "DHS Data", "MIS 2016", "MDKR71FL"),
      here("data", "DHS Data", "MIS 2016", "MDPR71FL")
    )
}
