# WARNING - Generated by {fusen} from dev/flat_linking_inputs.Rmd: do not edit by hand # nolint: line_length_linter.

#' Title
#' 
#' Description
#' 
#' @return
#' @importFrom purrr map_chr
#' @importFrom here here
#' @export
#' @examples
#' link_inputs("config.yml") %>%
#'   list_raw_gps_covars()
list_raw_gps_covars <- function(file_list){
    
    gps_covars <- stringr::str_subset(file_list, "MDGC[0-9]{2}FL.csv$")
    return(gps_covars)
}
