# WARNING - Generated by {fusen} from dev/flat_linking_inputs.Rmd: do not edit by hand # nolint: line_length_linter.

#' Title
#' 
#' Ingest the list of files in the project and return those that are GPS DHS files
#' 
#' @param file_list Character vector of file paths to check.
#'
#' @return Character vector of GPS DHS file paths.
#' @importFrom here here
#' @export
#' @examples
#' link_inputs("config.yml") %>%
#'   list_raw_gps_dhs()
list_raw_gps_dhs <- function(file_list){

  # Filter the file list to include only GPS DHS files
  gps_files <- stringr::str_subset(file_list, "MDGE[0-9]{2}FL.shp$")

  return(gps_files)
}
