# WARNING - Generated by {fusen} from dev/flat_load_dhs_data.Rmd: do not edit by hand # nolint: line_length_linter.

#' Title
#' 
#' Description
#' 
#' @return
#' 
#' @export
#' @examples
#' ex_data <- here("data", "DHS Data", "DHS 1997", "GPS Data", "MDGC32FL") %>%
#'   list.files(full.names = TRUE) %>%
#'   grep(pattern = "csv$", value = TRUE)
#' load_gps_covars(ex_data) %>%
#'   skimr::skim()
load_gps_covars <- function(fpath, factor_vars = c("DHSCLUST", "DHSID", "DHSCC", "GPS_Dataset")) {
  
  gps_covars <- readr::read_csv(fpath, na = c("", "NA", "-9999")) %>%
    dplyr::mutate(dplyr::across(dplyr::all_of(factor_vars), as.factor)) %>%
    dplyr::mutate(dplyr::across(where(is.character), as.factor))
  
  return(gps_covars)
}
