# WARNING - Generated by {fusen} from dev/flat_load_dhs_data.Rmd: do not edit by hand # nolint: line_length_linter.

#' load_flat_dhs_data Title
#'
#' @return 1
#' @export
#'
#' @examples
#' ex_data <- here("data", "DHS Data", "DHS 1992", "MDIR21FL")
#' load_flat_dhs_data(ex_data) %>%
#'   tibble() %>%
#'   head()
load_flat_dhs_data <- function(folder_path) {
  
  temp_zip <- tempfile(fileext = ".zip")
  zip::zipr(zipfile = temp_zip, files = list.files(folder_path, full.names = TRUE))
  dhs_data <- rdhs:::read_dhs_flat(temp_zip)
  return(dhs_data)

}
