# WARNING - Generated by {fusen} from dev/flat_load_dhs_data.Rmd: do not edit by hand # nolint: line_length_linter.

#' Title
#' 
#' Description
#' 
#' @return
#' 
#' @export
summarize_dhs_flat_dictionary <- function(all_survey_data){
  
  n_surveys <- length(all_survey_data) # shows the number of branches   

  map(
    all_survey_data,
    ~ get_variable_labels(.x) %>%
      as_tibble()
    ) %>%
    list_rbind() %>%
    group_by(description, variable) %>%
    summarise(
      description = first(description),
      n = n()
    ) %>%
    arrange(-n) -> var_descriptions

  return(var_descriptions)
}
